# NAMESPACE
apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    environment: production

# CONFIGMAP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: production
data:
  APP_ENV: "production"
  LOG_LEVEL: "info"
  APP_MODE: "nginx-app"

# SECRET
--- 
apiVersion: v1
kind: Secret
metadata: 
  name: app-secret
  namespace: production
type: Opaque
data: 
  DB_USER: YWRtaW4=       # admin
  DB_PASS: cGFzc3dvcmQ=   # password

# SERVICE ACCOUNT
---
apiVersion: v1
kind: ServiceAccount
metadata: 
  name: app-sa
  namespace: production

# DEPELOYMENT
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-app
  namespace: production

spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels: 
        app: nginx-app
    spec: 
      serviceAccountName: app-sa
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80

          env: 
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: APP_ENV

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DB_USER

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5

# SERVICE
---
apiVersion: v1
kind: Service
metadata: 
  name: nginx-service
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: nginx-app
  ports:
    - port: 80
      targetPort: 80

# INGRESS
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: nginx-ingress
  namespace: production
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: nginx.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend: 
              service:
                name: nginx-service
                port: 
                  number: 80

# HPA AUTO SCALING
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: 
  name: nginx-hpa
  namespace: production
spec: 
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-app
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:  
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60

# POD DISRUPTION BUDGET
--- 
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: nginx-pdb
  namespace: production
spec:
  minAvailable: 2
  selector: 
    matchLabels:
      app: nginx-app