apiVersion: apps/v1
kind: Deployment
metadata: 
  name: my-website  
  namespace: "my-webapp"
spec:
  replicas: 2
  selector: 
    matchLabels: 
      app: my-website 
  template:
    metadata:         
      labels: 
        app: my-website
    spec:
      containers:
        - name: my-website
          image: kalitesthub/my-web-app:v1.5 
          ports:  
            - containerPort: 80